baseURL = 'https://yalinpala.dev/'
languageCode = 'en-us'
title = "yp's home page"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  [markup.highlight]
    style = 'catppuccin-frappe'